#' A function to fit the logistic regression models to compare different types of predicted components
#' This function loads the saved RData file generated by data_application function
#' @export logistic_application
#' @param which_ear Either "right" or "left" to choose which ear of data is loaded
#' @param num_rep The number of resampling to overcome highly skewed class distribution in data
#' @return A list that contains the table of the averaged AUC values for different knot settings
#' @importFrom pROC roc auc
#' @importFrom stats glm binomial predict


logistic_application <- function(which_ear = "right", num_rep = 1000){

  ### 1. Read in data and group labels into two categories
  real_data <- read_real_data(select_ear = which_ear)
  data_ready <- real_data$data_ready
  labels_mat <- real_data$labels_mat

  if(which_ear == "right"){
    load("real_data_app_right.RData")

    labels_mat$colors <- "blue"
    labels_mat$colors[labels_mat$AUATYMTR=="Type AS"] <- "blue"
    labels_mat$colors[labels_mat$AUATYMTR=="Type AD"] <- "blue"
    labels_mat$colors[labels_mat$AUATYMTR=="Type B"] <- "red"
    labels_mat$colors[labels_mat$AUATYMTR=="Type C"] <- "red"
    labels_mat$colors[labels_mat$AUATYMTR=="88888"] <- "remove"
    labels_mat$colors[labels_mat$AUATYMTR=="99999"] <- "remove"
    # Normal labels are "blue", and the rest are "red"
    # Labels of error code are excluded

  } else if(which_ear == "left"){
    load("real_data_app_left.RData")

    labels_mat$colors <- "blue"
    labels_mat$colors[labels_mat$AUATYMTL=="Type AS"] <- "blue"
    labels_mat$colors[labels_mat$AUATYMTL=="Type AD"] <- "blue"
    labels_mat$colors[labels_mat$AUATYMTL=="Type B"] <- "red"
    labels_mat$colors[labels_mat$AUATYMTL=="Type C"] <- "red"
    labels_mat$colors[labels_mat$AUATYMTL=="88888"] <- "remove"
    labels_mat$colors[labels_mat$AUATYMTL=="99999"] <- "remove"
    # Normal labels are "blue", and the rest are "red"
    # Labels of error code are excluded
  }

  len_results_list <- length(results_list)
  # the total number of knot settings used in data_application function


  ### 2. Run repetition of resampling for "blue" class and model fitting
  set.seed(12345)
  result_list_all <- list()
  for(k in 1:num_rep){

    cat(k, "th iteration \n")

    ### 3. Prepare for recording and resampling
    record_logistic_mat <- matrix(0, len_results_list, 9)
    logistic_results_list <- list()

    sampled_blue <- sample(labels_mat$SEQN[labels_mat$colors == "blue"], table(labels_mat$colors)[2] * 2, replace=F)
    fixed_red <- labels_mat$SEQN[labels_mat$colors == "red"]
    train_seqn <- c(sampled_blue, fixed_red)


    ### 4. Iteration over knot settings used in data_application function
    for(i in 1:len_results_list){
      #  cat(i, "th iteraton \n")

      ### 5. Model 1 fitting
      scores_functional <- results_list[[i]]$fit_face$scores[,1:3]

      data_points <-  data.frame( "SEQN"=labels_mat$SEQN, scores_functional , labels_mat$colors)
      data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:5]

      colnames(data_logistic) <- c("X1", "X2", "X3", "colors")

      data_logistic$colors <- factor(data_logistic$colors)
      data_logistic1 <- data_logistic

      logistic_fit1 <- glm(colors ~ ., data=data_logistic1, family= binomial())

      pred_logistic <-predict(logistic_fit1, type="response")
      roc_obj<- roc(response=data_logistic1$colors, predictor = pred_logistic,  quiet = TRUE)
      record_logistic_mat[i,1] <- auc(roc_obj)



      ### 6. Model 2 fitting
      pca_multivariate <- prcomp(z_sample_std_mat, center = FALSE, scale=FALSE )
      scores_multivariate <- pca_multivariate$x[, 1:3]

      data_points <-  data.frame( "SEQN"=labels_mat$SEQN, scores_multivariate , labels_mat$colors)
      data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:5]

      colnames(data_logistic) <- c("X1", "X2", "X3", "colors")

      data_logistic$colors <- factor(data_logistic$colors)
      data_logistic2 <- data_logistic

      logistic_fit2 <- glm(colors ~ ., data=data_logistic2, family= binomial())


      pred_logistic <-predict(logistic_fit2, type="response")
      roc_obj<- roc(response=data_logistic2$colors, predictor = pred_logistic, quiet = TRUE)
      record_logistic_mat[i,2] <- auc(roc_obj)




      ### 7. Model 6 fitting
      scores_f3PlusM3 <- cbind(scores_functional[,1:3], pca_multivariate$x[, 1:3])

      data_points <-  data.frame( "SEQN"=labels_mat$SEQN, scores_f3PlusM3 , labels_mat$colors)
      data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:8]

      colnames(data_logistic) <- c("X1", "X2", "X3","X4","X5","X6", "colors")

      data_logistic$colors <- factor(data_logistic$colors)
      data_logistic6 <- data_logistic

      logistic_fit6 <- glm(colors ~ ., data=data_logistic6, family= binomial())


      pred_logistic <-predict(logistic_fit6, type="response")
      roc_obj<- roc(response=data_logistic6$colors, predictor = pred_logistic, quiet = TRUE)
      record_logistic_mat[i,6] <- auc(roc_obj)



      ### 8. Model 3 fitting
      score_common <- t( results_list[[i]]$Blup_pred_com )

      if(dim(score_common)[2]==2){

        data_points <-  data.frame( "SEQN"=labels_mat$SEQN, score_common , labels_mat$colors)
        data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:4]


        colnames(data_logistic) <- c("X1", "X2", "colors")
        data_logistic$colors <- factor(data_logistic$colors)
        data_logistic3 <- data_logistic

        logistic_fit3 <- glm(colors ~ ., data=data_logistic3, family= binomial())


        pred_logistic <-predict(logistic_fit3, type="response")
        roc_obj<- roc(response=data_logistic3$colors, predictor = pred_logistic, quiet = TRUE)
        record_logistic_mat[i,3] <- auc(roc_obj)




      } else {

        data_points <-  data.frame( "SEQN"=labels_mat$SEQN, score_common[,1:3] , labels_mat$colors)
        data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:5]

        colnames(data_logistic) <- c("X1", "X2", "X3", "colors")
        data_logistic$colors <- factor(data_logistic$colors)
        data_logistic3 <- data_logistic
        logistic_fit3 <- glm(colors ~ ., data=data_logistic3, family= binomial())


        pred_logistic <-predict(logistic_fit3, type="response")
        roc_obj<- roc(response=data_logistic3$colors, predictor = pred_logistic, quiet = TRUE)
        record_logistic_mat[i,3] <- auc(roc_obj)
      }



      ### 9. Model 5 fitting
      score_multivariate_ind <-  t(  results_list[[i]]$Blup_pred_ind_multi   )

      data_points <-  data.frame( "SEQN"=labels_mat$SEQN, score_multivariate_ind , labels_mat$colors)
      data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:5]

      colnames(data_logistic) <- c("X1", "X2", "X3", "colors")
      data_logistic$colors <- factor(data_logistic$colors)
      data_logistic5 <- data_logistic

      logistic_fit5 <- glm(colors ~ ., data=data_logistic5, family= binomial())


      pred_logistic <-predict(logistic_fit5, type="response")
      roc_obj<- roc(response=data_logistic5$colors, predictor = pred_logistic, quiet = TRUE)
      record_logistic_mat[i,5] <- auc(roc_obj)




      ### 10. Model 4 fitting
      score_functional_ind <- t( results_list[[i]]$Blup_pred_ind_func  )

      data_points <-  data.frame( "SEQN"=labels_mat$SEQN, score_functional_ind , labels_mat$colors)
      data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:5]

      colnames(data_logistic) <- c("X1", "X2", "X3", "colors")
      data_logistic$colors <- factor(data_logistic$colors)
      data_logistic4 <- data_logistic

      logistic_fit4 <- glm(colors ~ ., data=data_logistic4, family= binomial())

      pred_logistic <-predict(logistic_fit4, type="response")
      roc_obj<- roc(response=data_logistic4$colors, predictor = pred_logistic, quiet = TRUE)
      record_logistic_mat[i,4] <- auc(roc_obj)



      ### 11. Model 9 fitting

      score_common_allInd <- cbind(score_common[,1:2], score_functional_ind[,1:2], score_multivariate_ind[,1:2])

      data_points <-  data.frame( "SEQN"=labels_mat$SEQN, score_common_allInd , labels_mat$colors)
      data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:8]


      colnames(data_logistic) <- c("X1", "X2", "X3","X4", "X5", "X6", "colors")
      data_logistic$colors <- factor(data_logistic$colors)
      data_logistic9 <- data_logistic

      logistic_fit9 <- glm(colors ~ ., data=data_logistic9, family= binomial())

      pred_logistic <-predict(logistic_fit9, type="response")
      roc_obj<- roc(response=data_logistic9$colors, predictor = pred_logistic, quiet = TRUE)
      record_logistic_mat[i,9] <- auc(roc_obj)




      ### 12. Model 7 fiting
      if(dim(score_common)[2]==2){
        score_common_indFunc <- cbind(score_common[,1:2], score_functional_ind[,1:3])

      } else {
        score_common_indFunc <- cbind(score_common[,1:3], score_functional_ind[,1:3])

      }

      if(dim(score_common)[2]==2){

        data_points <-  data.frame( "SEQN"=labels_mat$SEQN, score_common_indFunc , labels_mat$colors)
        data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:7]

        colnames(data_logistic) <- c("X1", "X2", "X3","X4", "X5", "colors")
      } else  {

        data_points <-  data.frame( "SEQN"=labels_mat$SEQN, score_common_indFunc , labels_mat$colors)
        data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:8]

        colnames(data_logistic) <- c("X1", "X2", "X3","X4", "X5", "X6", "colors")
      }

      data_logistic$colors <- factor(data_logistic$colors)

      data_logistic7 <- data_logistic
      logistic_fit7 <- glm(colors ~ ., data=data_logistic7, family= binomial())


      pred_logistic <-predict(logistic_fit7, type="response")
      roc_obj<- roc(response=data_logistic7$colors, predictor = pred_logistic, quiet = TRUE)
      record_logistic_mat[i,7] <- auc(roc_obj)




      ### 13. Model 8 fitting

      if(dim(score_common)[2]==2){
        score_common_indMulti <- cbind(score_common[,1:2], score_multivariate_ind[,1:3])

      } else {
        score_common_indMulti <- cbind(score_common[,1:3], score_multivariate_ind[,1:3])

      }


      if(dim(score_common)[2]==2){

        data_points <-  data.frame( "SEQN"=labels_mat$SEQN, score_common_indMulti , labels_mat$colors)
        data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:7]

        colnames(data_logistic) <- c("X1", "X2", "X3","X4", "X5", "colors")
      } else   {

        data_points <-  data.frame( "SEQN"=labels_mat$SEQN, score_common_indMulti , labels_mat$colors)
        data_logistic <- data_points[(data_points$SEQN %in% train_seqn)   , 2:8]

        colnames(data_logistic) <- c("X1", "X2", "X3","X4", "X5", "X6", "colors")
      }

      data_logistic$colors <- factor(data_logistic$colors)

      data_logistic8 <- data_logistic
      logistic_fit8 <- glm(colors ~ ., data=data_logistic8, family= binomial())

      pred_logistic <-predict(logistic_fit8, type="response")
      roc_obj<- roc(response=data_logistic8$colors, predictor = pred_logistic, quiet = TRUE)
      record_logistic_mat[i,8] <- auc(roc_obj)


      #    logistic_results_list[[i]] = list(
      #      "logistic_fit1"=logistic_fit1,
      #      "logistic_fit2"=logistic_fit2,
      #      "logistic_fit3"=logistic_fit3,
      #      "logistic_fit4"=logistic_fit4,
      #      "logistic_fit5"=logistic_fit5,
      #      "logistic_fit6"=logistic_fit6,
      #      "logistic_fit7"=logistic_fit7,
      #      "logistic_fit8"=logistic_fit8,
      #      "logistic_fit9"=logistic_fit9

      #    )
    }
    result_list_all[[k]] <- list(
      #    "logistic_results_list"=logistic_results_list ,
      "record_logistic_mat"=record_logistic_mat,
      "train_seqn"=train_seqn
    )
  }

  ### 14. Average of AUC values over iterations
  auc_mean_mat <- matrix(0, len_results_list, 9)
  for(j in 1:len_results_list){
    k1 <- matrix(0,num_rep,9)

    for(k in 1:num_rep){
      k1[k, ] <- result_list_all[[k]]$record_logistic_mat[j, ]
    }
    auc_mean_mat[j,] <- colMeans(k1)
  }


  colnames(auc_mean_mat) <- c("Fun", "Mul", "Com", "Fun_ind", "Mul_ind", "Fun+Mul", "Com+Fun_ind", "Com+Mul_ind", "Com+FunMul_ind")

  if(which_ear == "right"){
    auc_mean_mat_right <- auc_mean_mat

    save(auc_mean_mat_right,
         file="logistic_application_right.RData")
  } else if(which_ear == "left"){
    auc_mean_mat_left <- auc_mean_mat

    save(auc_mean_mat_left,
         file="logistic_application_left.RData")
  }
  res <-  list("auc_mean_mat"= auc_mean_mat, "which_ear" = which_ear)
  return( res )
} ## end of function

